[theme]
primaryColor="#F56600"              # Clemson Orange
backgroundColor="#FFFFFF"           # WHITE MAIN BACKGROUND
secondaryBackgroundColor="#F6F1EB"  # Light beige sidebar (Clemson)
textColor="#333333"                 # Dark gray text
font="sans serif"